import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chess.com Play Chess Online-Free Games",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex ">
          <div className="fixed ">
          
        <div className="bg-[#262522] font-semibold text-white h-screen flex flex-col w-36 cursor-pointer  ">
          <div className="bg-white">
        <img src="https://logowik.com/content/uploads/images/chesscom2309.logowik.com.webp" alt="Chess.comLogo" className="h-14 bg-white  w-28 bg-transparent "   />
          </div>

        <div className="flex p-2 m-1 justify-start gap-4 items-center hover:bg-[#21201E] rounded cursor-pointer ">
          <img src="https://www.animatedimages.org/data/media/613/animated-chess-image-0074.gif" alt="Play" width={35} />
          Play
        </div>
        <div className="flex p-2 m-1 justify-start gap-4 items-center hover:bg-[#21201E] rounded cursor-pointer">
          <img src="https://cdn-icons-png.flaticon.com/128/993/993686.png" alt="Puzzles" width={35} />
          Puzzles
        </div>
        <div className="flex p-2  justify-start gap-4 items-center hover:bg-[#21201E] rounded cursor-pointer">
          <img src="https://cdn-icons-png.flaticon.com/128/8637/8637091.png" alt="Learn" width={35} />
          Learn
        </div>
        <div className="flex p-2  justify-start gap-4 items-center hover:bg-[#21201E] rounded cursor-pointer">
          <img src="https://cdn-icons-png.flaticon.com/128/4221/4221419.png" alt="Watch" width={35} />
          Watch
        </div>
          <div className="flex p-2  justify-start gap-4 items-center hover:bg-[#21201E] rounded cursor-pointer">
            <img src="https://cdn-icons-png.flaticon.com/128/2540/2540832.png" alt="News" width={35} />
            News
          </div >
          <div className="flex p-2  justify-start gap-4 items-center hover:bg-[#21201E] rounded cursor-pointer">
            <img src="https://cdn-icons-png.flaticon.com/128/16134/16134295.png" alt="Social" width={35} />
            Social
          </div>
          <div className="flex p-2  justify-start gap-4 items-center hover:bg-[#21201E] rounded cursor-pointer">
            <img src="https://cdn-icons-png.flaticon.com/128/14849/14849048.png" alt="More" width={35} />
            More
          </div>
          <input type="text" placeholder="Search" className="rounded p-1 bg-[#454341] font-medium text-sm py-2  m-2  " />
          <button className="bg-[#81B64C] p-1 rounded font-medium  m-2 hover:bg-[#9CCA5D] ">Sign Up</button>
          <button className="bg-[#454341] p-1 rounded font-medium text-[#989795] hover:bg-[#4D4C49]  m-2 ">Log In</button>

        <div className="bg-[#262522] p-1 rounded  text-[#989795] font-bold  hover:bg-[#21201E] flex justify-center mt-96 items-center gap-3  m-2 ">
          <div><img src="https://cdn-icons-png.flaticon.com/128/5790/5790602.png" width={30} alt="" /></div>
          <div>English</div>
        </div>

        <div className="bg-[#262522] p-1 rounded  text-[#989795] font-bold  hover:bg-[#21201E] flex justify-center items-center gap-3  m-2 ">
          <div><img src="https://cdn-icons-png.flaticon.com/128/2600/2600350.png" width={30} alt="" /></div>
          <div>Support</div>
        </div>
        </div>

        </div>
        {children}
        </div>
      </body>
    </html>
  );
}
